# fly.toml app configuration file generated for helpscout-response-evaluator-zi8jjg on 2025-10-01T12:04:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helpscout-response-evaluator-zi8jjg'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
